name: TAB-Bridge
version: ${project.version}
author: NEZNAMY
main: me.neznamy.tab.bridge.bukkit.BukkitBridge
api-version: 1.13
website: "https://www.mc-market.org/resources/21641/"
softdepend: [PlaceholderAPI, Vault]
description: "Bukkit bridge for PlaceholderAPI support when TAB is on bungeecord"